# Generated by Django 5.1 on 2024-09-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_rename_bio_business_project_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='applications',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
