# Generated by Django 5.1 on 2024-09-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_business_applications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='applications',
            field=models.IntegerField(default=1),
        ),
    ]
